### ISSUE TITLE
POST method is not working with HTTP 301 redirect - Swift 2 - Xcode 7.4 - Alamofire 1.3.0

### ISSUE THREAD

**Issue by henriquesobral** [Alamofire/Alamofire#649]
Hi, I'm trying to request a POST method using Alamofire. I'm using Heroku, and to have a root domain, it needs a HTTP redirect to work. But the Alamofire (i think), isn't applying the HTTP Method on redirect.

The method request with "www":
```swift
    Alamofire.request(.POST, "http://www.example.com/registrations.json").responseJSON(completionHandler: {(req, res, data) in
      switch data {
      case .Success(let json):
        let user = User(json: JSON(json))
        self.myApplication.storeUser(user)
        self.goNext()
      case .Failure(let data, let error):
        print(req, appendNewline: true)
        print(res, appendNewline: true)
        print(data, appendNewline: true)
        print(error, appendNewline: true)
      }
    })
```

Heroku server log with "www", been hit with 'POST':
```
015-08-05T22:24:50.143366+00:00 app[web.1]: Started POST "/registrations.json" for 187.122.124.193 at 2015-08-05 22:24:50 +0000
2015-08-05T22:24:50.217193+00:00 app[web.1]: Can't verify CSRF token authenticity
2015-08-05T22:24:50.360367+00:00 app[web.1]:    (4.7ms)  BEGIN
2015-08-05T22:24:50.194227+00:00 app[web.1]: Processing by RegistrationsController#create as JSON
2015-08-05T22:24:50.217755+00:00 app[web.1]: Geokit is using the domain: example.com
2015-08-05T22:24:50.381985+00:00 app[web.1]:   SQL (4.9ms)  INSERT INTO `users` (`profile`, `created_at`, `updated_at`) VALUES ('guest', '2015-08-05 22:24:50', '2015-08-05 22:24:50')
2015-08-05T22:24:50.434167+00:00 app[web.1]:   ApiKey Load (6.3ms)  SELECT  `api_keys`.* FROM `api_keys` WHERE `api_keys`.`user_id` = 32 AND (created_at <= '2015-08-05 22:24:50.423325' AND expires_at >= '2015-08-05 22:24:50.423325') LIMIT 1
2015-08-05T22:24:50.683762+00:00 app[web.1]:   Person Load (3.1ms)  SELECT  `people`.* FROM `people` WHERE `people`.`personable_id` = 32 AND `people`.`personable_type` = 'User' LIMIT 1
2015-08-05T22:24:50.617984+00:00 app[web.1]:   SQL (4.4ms)  INSERT INTO `api_keys` (`user_id`, `created_at`, `updated_at`, `access_token`, `expires_at`) VALUES (32, '2015-08-05 22:24:50', '2015-08-05 22:24:50', 'eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NDE0OTE4OTAsInYiOjAsImlhdCI6MTQzODgxMzQ5MCwiZCI6eyJ1aWQiOiIzMiIsInByb2ZpbGUiOiJndWVzdCIsImlkIjoiMzIifX0.FQfctD82t80UJjUg0_YL-GOn4emETqOGcVfr6-fPX00', '2015-09-05 22:24:50')
2015-08-05T22:24:50.626442+00:00 app[web.1]:    (5.3ms)  COMMIT
2015-08-05T22:24:51.072576+00:00 heroku[router]: at=info method=POST path="/registrations.json" host=www.example.com request_id=ee58ddb9-d3d3-4f90-8723-b9869ce2ef14 fwd="187.122.124.193" dyno=web.1 connect=3ms service=952ms status=201 bytes=716
2015-08-05T22:24:51.054487+00:00 app[web.1]: Completed 201 Created in 860ms (Views: 54.3ms | ActiveRecord: 60.6ms)
2015-08-05T22:24:51.033541+00:00 app[web.1]:   ApiKey Load (4.2ms)  SELECT  `api_keys`.* FROM `api_keys` WHERE `api_keys`.`user_id` = 32 AND (created_at <= '2015-08-05 22:24:51.027693' AND expires_at >= '2015-08-05 22:24:51.027693')  ORDER BY `api_keys`.`id` ASC LIMIT 1
2015-08-05T22:24:51.053974+00:00 app[web.1]:   Rendered registrations/show.json.jbuilder (18.4ms)
```

The method request without "www":
```swift
    Alamofire.request(.POST, "http://example.com/registrations.json").responseJSON(completionHandler: {(req, res, data) in
      switch data {
      case .Success(let json):
        let user = User(json: JSON(json))
        self.myApplication.storeUser(user)
        self.goNext()
      case .Failure(let data, let error):
        print(req, appendNewline: true)
        print(res, appendNewline: true)
        print(data, appendNewline: true)
        print(error, appendNewline: true)
      }
    })
```

Heroku server log without "www" , been hit with 'GET':
```
2015-08-06T15:28:04.642498+00:00 app[web.1]: Started GET "/registrations.json" for 187.122.124.193 at 2015-08-06 15:28:04 +0000
2015-08-06T15:28:04.756790+00:00 heroku[router]: at=info method=GET path="/registrations.json" host=www.example.com request_id=6a81c787-c720-47a0-9574-1b0f101a2279 fwd="187.122.124.193" dyno=web.1 connect=1ms service=126ms status=404 bytes=1744
2015-08-06T15:28:04.754988+00:00 app[web.1]:
2015-08-06T15:28:04.754994+00:00 app[web.1]: ActionController::RoutingError (No route matches [GET] "/registrations.json"):
2015-08-06T15:28:04.754996+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:21:in `call'
2015-08-06T15:28:04.754997+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
2015-08-06T15:28:04.754999+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:38:in `call_app'
2015-08-06T15:28:04.755000+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `block in call'
2015-08-06T15:28:04.755002+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:26:in `tagged'
2015-08-06T15:28:04.755001+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `block in tagged'
2015-08-06T15:28:04.755003+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/tagged_logging.rb:68:in `tagged'
2015-08-06T15:28:04.755004+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/rack/logger.rb:20:in `call'
2015-08-06T15:28:04.755005+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/request_id.rb:21:in `call'
2015-08-06T15:28:04.755007+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
2015-08-06T15:28:04.755008+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
2015-08-06T15:28:04.755009+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
2015-08-06T15:28:04.755010+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/actionpack-4.2.3/lib/action_dispatch/middleware/static.rb:116:in `call'
2015-08-06T15:28:04.755011+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
2015-08-06T15:28:04.755012+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/engine.rb:518:in `call'
2015-08-06T15:28:04.755014+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/railties-4.2.3/lib/rails/application.rb:165:in `call'
2015-08-06T15:28:04.755021+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/configuration.rb:53:in `call'
2015-08-06T15:28:04.755022+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/server.rb:539:in `handle_request'
2015-08-06T15:28:04.755023+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/server.rb:386:in `process_client'
2015-08-06T15:28:04.755024+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/server.rb:269:in `block in run'
2015-08-06T15:28:04.755025+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/thread_pool.rb:106:in `call'
2015-08-06T15:28:04.755026+00:00 app[web.1]:   vendor/bundle/ruby/2.2.0/gems/puma-2.12.2/lib/puma/thread_pool.rb:106:in `block in spawn_thread'
```

**Comment by cnoon** [comment]
Hi @henriquesobral,

You should try to override the following task override closure on the session to attempt to track down what's going on.

```swift
/// Overrides default behavior for NSURLSessionTaskDelegate method `URLSession:task:willPerformHTTPRedirection:newRequest:completionHandler:`.
public var taskWillPerformHTTPRedirection: ((NSURLSession, NSURLSessionTask, NSHTTPURLResponse, NSURLRequest) -> NSURLRequest?)?
```

You can set this closure by:

```swift
let manager = Alamofire.Manager()
manager.delegate. taskWillPerformHTTPRedirection = { session, task, response, request in
    print(request)
    return request
}
```

That should at least help you debug.

**Comment by cnoon** [comment]
Hi @henriquesobral, if you could get back to me by the end of the weekend I would appreciate it. Otherwise I'm going to close this issue out. 

None of this behavior should be caused by Alamofire itself. Alamofire let's the redirection happen exactly as Apple intended while exposing the `taskWillPerformRedirection` closure to override the behavior as I mentioned before.

**Comment by cnoon** [comment]
I'm going to close this issue out. @henriquesobral if you end up finding the root issue is actually a problem with Alamofire, please comment on this issue and I'll re-open it. 

Cheers.

**Comment by ckrey** [comment]
NSURLSession replaces the HTTPMethod "Post" by "Get" when it receives a redirection.
Not sure if this is the intended behaviour, but it is definetly not expected

**Comment by StarWars** [comment]
@ckrey Thank your for mentioning that.
